apps/blog/urls.py
from django.urls import path
from .views import home, blog_view, about_view, rent_view, blog_single

urlpatterns = [
    path('', home),
    path('blog/', blog_view),
    path('about/', about_view),
    path('rent/<int:pk>/', rent_view),
    path('detail/<int:pk>/', blog_single),
]

apps/cars/urls.py
from django.urls import path
from .views import cars_view

urlpatterns = [
    path('', cars_view),
]

apps/contact/urls.py
from django.urls import path
from .views import contact

urlpatterns = [
    path('', contact)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls')),
    path('contact/', include('apps.contact.urls')),
    path('service/', include('apps.services.urls')),
    path('cars/', include('apps.cars.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from apps.profiles.models import Profile


class About(models.Model):
    title = models.CharField(max_length=221)
    image = models.ImageField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Team(models.Model):
    ROLES = (
        (0, 'Stuff'),
        (1, 'Manager'),
        (2, 'Founder')
    )
    name = models.CharField(max_length=221)
    avatar = models.ImageField()
    role = models.IntegerField(choices=ROLES)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class History(models.Model):
    title = models.CharField(max_length=221)
    image = models.ImageField()
    history = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class HowItWorks(models.Model):
    hiw_num = models.IntegerField()
    hiw_title = models.CharField(max_length=221)

    def __str__(self):
        return self.hiw_title


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

apps/cars/models.py
from django.db import models


class Cars(models.Model):
    TRANS = (
        ('None', 'None'),
        ('Mechanic', 'Mechanic'),
        ('Automatic', 'Automatic'),
        ('AI', 'AI')
    )
    PRICE = (
        ('$', '$'),
        ('Euro', 'Euro'),
    )
    name = models.CharField(max_length=221)
    image = models.ImageField(upload_to='media/')
    price = models.IntegerField()
    price_value = models.CharField(max_length=50, choices=PRICE, default='$')
    doors = models.IntegerField()
    seats = models.IntegerField()
    trans = models.CharField(max_length=50, choices=TRANS, default='None')
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Book(models.Model):
    where_from = models.CharField(max_length=221)
    where_to = models.CharField(max_length=221)
    go_date = models.DateTimeField()
    back_date = models.DateTimeField()
    car = models.ForeignKey(Cars, on_delete=models.CASCADE, related_name='books')

    def __str__(self):
        return self.where_to

apps/comment/models.py
from django.db import models
from apps.profiles.models import Profile
from apps.blog.models import Article


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def str(self):
        return self.name

apps/contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=221)
    phone = models.CharField(max_length=221)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

apps/services/models.py
from django.db import models


class Service(models.Model):
    icon = models.ImageField()
    title = models.CharField(max_length=221)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/cars/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = filed_name.capitalize()

apps/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = filed_name.capitalize()

apps/blog/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Article, About, Team, History, HowItWorks, Category
from apps.services.models import Service
from apps.cars.models import Cars
from apps.cars.forms import BookForm, Book
from apps.feedback.models import FeedBack
from apps.comment.forms import CommentForm
from django.http import Http404


def home(request):
    cars = Cars.objects.all().order_by('-id')[:1]
    cars_single = Cars.objects.all()
    blog = Article.objects.all().order_by('-id')[:3]
    objects = Service.objects.all()
    step_by_step = HowItWorks.objects.all()
    back = FeedBack.objects.all().order_by('-id')[:3]
    form = BookForm()
    if request.method == 'POST':
        form = BookForm(request.POST)
        sd = request.POST.get('sd')
        ed = request.POST.get('ed')
        free_cars = Cars.objects.filter(~Q(books__go_date__range=[sd, ed]) or ~Q(books__back_date__range=[sd, ed]))
        print(sd)
        print(ed)
        print(free_cars)

    count = Cars.objects.all().count()
    # if form.is_valid():
    #    form.save()
    #     return redirect('/')
    context = {
        'post': blog,
        'service': objects,
        'item': cars,
        'item_2': cars_single,
        'hiw': step_by_step,
        'form': form,
        'count': count,
        'feed': back,
    }
    return render(request, 'index.html', context)


def rent_view(request, pk):
    sd = request.GET.get('sd')
    ed = request.GET.get('ed')
    from_ = request.GET.get('from_')
    to_ = request.GET.get('to_')
    print(sd)
    print(ed)
    print(from_)
    print(to_)
    if request.method == 'POST':
        Book.objects.create(
            car_id=pk,
            where_from=from_,
            where_to=to_,
            go_date=sd,
            back_date=ed
        )
    car = request.GET.get('car')
    obj = Cars.objects.get(id=pk)
    if car:
        objs = obj.filter(name__icontains=car)
        return objs
    context = {
        'obj': obj,
    }
    return render(request, 'rent.html', context)


def blog_view(request):
    blog = Article.objects.all()
    step_by_step = HowItWorks.objects.all()
    page_number = request.GET.get('page')
    p = Paginator(blog, 1)
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    context = {
        'post': blog,
        'obj': step_by_step,
        'page': page_obj
    }
    return render(request, 'blog.html', context)


def about_view(request):
    about = About.objects.all()
    team = Team.objects.all()
    history = History.objects.all()
    step_by_step = HowItWorks.objects.all()
    for i in team:
        print(i.role)
    context = {
        'abouts': about,
        'hist': history,
        'people': team,
        'obj': step_by_step
    }
    return render(request, 'about.html', context)


def blog_single(request, pk=None):
    # if pk is not None:
    post = Article.objects.get(id=pk)
    categories = Category.objects.all().order_by('-id')
    user = request.user
    author = user.profile
    form = CommentForm()
    cat = request.GET.get('category')
    if cat:
        post = post.filter(title__icontains=cat)
        return post
    if request.method == "POST":
        if user.is_authenticated:
            form = CommentForm(request.POST, request.FILES)
            if form.is_valid():
                com = form.save(commit=False)
                com.post = post
                com.author = author
                com.save()
                return redirect('/')
        # some error
        return Http404
    context = {
        'article': post,
        'categories': categories,
        'form': form
    }
    return render(request, 'single.html', context)

apps/cars/views.py
from django.db.models import Q
from django.shortcuts import render

from .models import Cars
from apps.blog.models import HowItWorks


def cars_view(request):
    sd = request.POST.get('sd')
    ed = request.POST.get('ed')
    from_ = request.POST.get('from_')
    to_ = request.POST.get('to_')
    free_cars = Cars.objects.filter(~Q(books__go_date__range=[sd, ed]) or ~Q(books__back_date__range=[sd, ed]))
    print(sd)
    print(ed)
    print(from_)
    print(to_)
    print(free_cars)
    step_by_step = HowItWorks.objects.all()
    context = {
        'obj': free_cars,
        'hiw': step_by_step,
        'sd': sd,
        'ed': ed,
        'from_': from_,
        'to_': to_
    }
    return render(request, 'cars.html', context)

apps/contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        # return redirect('contact:contact')
    context = {
        'form': form
    }
    return render(request, 'contact.html', context)

apps/services/views.py
from django.shortcuts import render
from .models import Service
from apps.blog.models import HowItWorks


def service_view(request):
    services = Service.objects.all()
    step_by_step = HowItWorks.objects.all()
    context = {
        'obj': services,
        'hiw': step_by_step
    }
    return render(request, 'services.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage"
         style="background-image:url({% static 'images/xhero_2.jpg.pagespeed.ic.KNUedOVkh2.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <h1>About Us</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row">
            {% for i in abouts %}
            <div class="col-lg-6 mb-5 mb-lg-0 order-lg-2">
                <img src="{{ i.image.url }}" alt="Image" class="img-fluid">
            </div>
            <div class="col-lg-4 mr-auto">
                <h2>{{ i.title }}</h2>
                <p>{{ i.desc }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center text-center mb-5 section-2-title">
            <div class="col-md-6">
                <span class="text-primary">Our Team</span>
                <h2 class="mb-4">Meet Our Team</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis provident eius ratione
                    velit, voluptas laborum nemo quas ad necessitatibus placeat?</p>
            </div>
        </div>
        <div class="row align-items-stretch">
            {% for p in people %}
                <div class="col-lg-4 col-md-6 mb-5">
                <div class="post-entry-1 h-100 person-1">
                    <img src="{{ p.avatar.url }}" alt="Image" class="img-fluid">
                    <div class="post-entry-1-contents">
                        <span class="meta">{{ p.get_role_display }}</span>
                        <h2>{{ p.name }}</h2>
                        <p>{{ p.bio }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row">
            {% for t in hist %}
                <div class="col-lg-6 mb-5 mb-lg-0">
                <img src="{{ t.image.url }}" alt="Image" class="img-fluid">
            </div>
                <div class="col-lg-4 ml-auto">
                <h2>{{ t.title }}</h2>
                <p>{{ t.history }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container site-section mb-5">
    <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
            <h2>How it works</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius
                earum voluptates sed!</p>
        </div>
    </div>
    <div class="how-it-works d-flex">
        {% for t in obj %}
            <div class="step">
            <span class="number"><span>{{ t.hiw_num }}</span></span>
            <span class="caption">{{ t.hiw_title }}</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage"
         style="background-image:url({% static 'images/xhero_2.jpg.pagespeed.ic.KNUedOVkh2.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <h1>Car Articles</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            {% for i in post %}
                <div class="col-lg-4 col-md-6 mb-4">
                <div class="post-entry-1 h-100">
                    <a href="/">
                        <img src="{{ i.image.url }}" alt="Image" class="img-fluid">
                    </a>
                    <div class="post-entry-1-contents">
                        <h2><a href="/detail/{{ i.id }}">{{ i.title }}</a></h2>
                        <span class="meta d-inline-block mb-3">{{ i.created_at }}<span class="mx-2">by</span> <a
                                href="/">{{ i.author }}</a></span>
                        <p>{{ i.content }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% for i in page.paginator.page_range %}
            <div class="col-12">
                {% if page.number == i %}
                <span class="p-3">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}" class="p-3">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container site-section mb-5">
    <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
            <h2>How it works</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius
                earum voluptates sed!</p>
        </div>
    </div>
    <div class="how-it-works d-flex">
        {% for j in obj %}
            <div class="step">
            <span class="number"><span>{{ j.hiw_num }}</span></span>
            <span class="caption">{{ j.hiw_title }}</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/cars.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage"
         style="background-image:url({% static 'images/xhero_2.jpg.pagespeed.ic.KNUedOVkh2.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <h1>Our For Rent Cars</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            {% for c in obj %}
                <div class="col-lg-4 col-md-6 mb-4">
                <div class="item-1">
                    <a href="#"><img src="{{ c.image.url }}" height="40px" width="400px" alt="Image"
                                     class="img-fluid"></a>
                    <div class="item-1-contents">
                        <div class="text-center">
                            <h3><a href="#">{{ c.name }}</a></h3>
                            <div class="rating">
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                            </div>
                            <div class="rent-price"><span>{{ c.price }}{{ c.price_value }}/</span>day</div>
                        </div>
                        <ul class="specs">
                            <li>
                                <span>Doors</span>
                                <span class="spec">{{ c.doors }}</span>
                            </li>
                            <li>
                                <span>Seats</span>
                                <span class="spec">{{ c.seats }}</span>
                            </li>
                            <li>
                                <span>Transmission</span>
                                <span class="spec">{{ c.get_trans_display }}</span>
                            </li>
                            <li>
                                <span>Minium age</span>
                                <span class="spec">{{ c.age }}</span>
                            </li>
                        </ul>
                        <div class="d-flex action">
                            <a href="/rent/{{ c.id }}?sd={{ sd }}&ed={{ ed }}&from_={{ from_ }}&to_={{ to_ }}" class="btn btn-primary">Rent Now</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-12">
                <span class="p-3">1</span>
                <a href="#" class="p-3">2</a>
                <a href="#" class="p-3">3</a>
                <a href="#" class="p-3">4</a>
            </div>
        </div>
    </div>
</div>
<div class="container site-section mb-5">
    <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
            <h2>How it works</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius
                earum voluptates sed!</p>
        </div>
    </div>
    <div class="how-it-works d-flex">
        {% for y in hiw %}
            <div class="step">
            <span class="number"><span>{{ y.hiw_num }}</span></span>
            <span class="caption">{{ y.hiw_title }}</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage"
         style="background-image:url({% static 'images/xhero_2.jpg.pagespeed.ic.KNUedOVkh2.jpg' %})">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <h1>Contact Us</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light" id="contact-section">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>Contact Us Or Use This Form To Rent A Car</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus
                    eius earum voluptates sed!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mb-5">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <!--<input type="text" class="form-control" placeholder="First name">-->
                            {{ form.name }}
                        </div>
                        <div class="col-md-6">
                            <!--<input type="text" class="form-control" placeholder="Phone number">-->
                            {{ form.phone }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <!--<input type="text" class="form-control" placeholder="Email address">-->
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                                <!--<textarea name="" id="" class="form-control" placeholder="Write your message." cols="30"
                                          rows="10"></textarea>-->
                            {{ form.message }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mr-auto">
                            <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5"
                                   value="Send Message">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 ml-auto">
                <div class="bg-white p-3 p-md-5">
                    <h3 class="text-black mb-4">Contact Info</h3>
                    <ul class="list-unstyled footer-link">
                        <li class="d-block mb-3">
                            <span class="d-block text-black">Address:</span>
                            <span>34 Street Name, City Name Here, United States</span></li>
                        <li class="d-block mb-3"><span
                                class="d-block text-black">Phone:</span><span>+1 242 4942 290</span></li>
                        <li class="d-block mb-3"><span class="d-block text-black">Email:</span><span><a
                                href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__"
                                data-cfemail="c3aaada5ac83baacb6b1a7acaea2aaadeda0acae">[email&#160;protected]</a></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/single.html
{% extends 'base.html' %}
{% block content %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 innerpage overlay"
         style="background-image:url({{ article.image.url }})">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                        <span class="d-block mb-3 text-white" data-aos="fade-up">{{ article.created_at }} <span
                                class="mx-2 text-primary">&bullet;</span> by {{ article.author }}</span>
                    <h1 class="mb-4" data-aos="fade-up" data-aos-delay="100">{{ article.title }}</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-content">
                <p class="lead">{{ article.content }}</p>
                <div class="pt-5">
                    <p>Categories: <a href="#">{{ article.category }}</a> Tags: <a href="#">#{{ article.tag }}</a></p>
                </div>
                <div class="pt-5">
                    <h3 class="mb-5">{{ article.comment_set.all.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in article.comment_set.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                {% if comment.author.avatar %}
                                <img src="{{ comment.author.avatar.url }}"
                                     alt="Free Website Template by Free-Template.co">
                                {% endif %}
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.author.full_name.title }}</h3>
                                <div class="meta">{{ comment.created_at }}</div>
                                <p>{{ comment.message }}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
<!--                            {% if comment.get_children %}-->
<!--                            <ul class="children">-->
<!--                                {% for i in comment.get_children %}-->
<!--                                <li class="comment">-->
<!--                                    <div class="vcard bio">-->
<!--                                        {% if i.author.avatar %}-->
<!--                                        <img src="{{ i.author.avatar.url }}"-->
<!--                                             alt="Free Website Template by Free-Template.co">-->
<!--                                        {% endif %}-->
<!--                                    </div>-->
<!--                                    <div class="comment-body">-->
<!--                                        <h3>{{ i.author.full_name.title }}</h3>-->
<!--                                        <div class="meta">{{ i.created_at }}</div>-->
<!--                                        <p>{{ i.message }}</p>-->
<!--                                        <p><a href="#leave_comment" data-comment_id="{{ i.id }}" data-top_level_comment_id="{{ i.top_level_comment_id }}" class="reply">Reply</a></p>-->
<!--                                    </div>-->

<!--                                </li>-->
<!--                                {% endfor %}-->
<!--                            </ul>-->
<!--                            {% endif %}-->
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="email">Email *</label>
<!--{#                                    <input type="email" class="form-control" id="email">#}-->
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
<!--{#                                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>#}-->
                                    {{ form.message }}
                                </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn btn-primary btn-md text-white">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box">
                    <div class="categories">
                        <h3>Categories</h3>
                        {% for c in categories %}
                           <li><a href="/detail/{{ c.id }}">{{ c.title }}<span>{{ c.category_set.all.count }}</span></a></li>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box">
                    <img src="{{ article.author.avatar.url }}"
                         alt="Free Website Template by Free-Template.co" class="img-fluid mb-4 w-50 rounded-circle">
                    <h3 class="text-black">About The Author</h3>
                    <p>{{ article.author.bio }}</p>
                    <p><a href="#" class="btn btn-primary btn-md text-white">Read More</a></p>
                </div>
                <div class="sidebar-box">
                    <h3 class="text-black">Paragraph</h3>
                    <p>{{ article.content }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}